// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  '/': {
    params: {};
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page: '/';
  };
  'layouts/main.tsx': {
    id: 'layouts/main';
    page: '/';
  };
  'routes/home.tsx': {
    id: 'routes/home';
    page: '/';
  };
};

type RouteModules = {
  root: typeof import('./app/root.tsx');
  'layouts/main': typeof import('./app/layouts/main.tsx');
  'routes/home': typeof import('./app/routes/home.tsx');
};
