import type { IconProps } from '../Icons.types';

const PricingIcon = ({
  className,
  height = 200,
  width = 220,
}: IconProps) => {
  return (
    <svg
      className={className}
      fill='none'
      height={height}
      viewBox='0 0 220 200'
      width={width}
      xmlns='http://www.w3.org/2000/svg'
    >
      {/* Background circles */}
      <circle
        cx='110'
        cy='100'
        fill='url(#pricingGradient1)'
        opacity='0.1'
        r='90'
      />
      <circle
        cx='110'
        cy='100'
        fill='url(#pricingGradient2)'
        opacity='0.15'
        r='70'
      />
      <circle
        cx='110'
        cy='100'
        fill='url(#pricingGradient3)'
        opacity='0.2'
        r='50'
      />

      {/* Membership card */}
      <rect
        fill='url(#pricingGradient4)'
        height='50'
        rx='8'
        stroke='url(#pricingGradient5)'
        strokeWidth='2'
        width='80'
        x='70'
        y='60'
      />
      <rect
        fill='rgba(255,255,255,0.8)'
        height='8'
        rx='4'
        width='70'
        x='75'
        y='65'
      />
      <rect
        fill='rgba(255,255,255,0.6)'
        height='6'
        rx='3'
        width='45'
        x='75'
        y='78'
      />
      <rect
        fill='rgba(255,255,255,0.6)'
        height='6'
        rx='3'
        width='35'
        x='75'
        y='88'
      />
      <circle
        cx='135'
        cy='85'
        fill='rgba(255,255,255,0.8)'
        r='8'
      />

      {/* Fitness elements - dumbbells */}
      <rect
        fill='url(#pricingGradient6)'
        height='8'
        rx='4'
        width='30'
        x='40'
        y='130'
      />
      <circle
        cx='35'
        cy='134'
        fill='url(#pricingGradient6)'
        r='6'
      />
      <circle
        cx='75'
        cy='134'
        fill='url(#pricingGradient6)'
        r='6'
      />

      <rect
        fill='url(#pricingGradient6)'
        height='8'
        rx='4'
        width='30'
        x='150'
        y='130'
      />
      <circle
        cx='145'
        cy='134'
        fill='url(#pricingGradient6)'
        r='6'
      />
      <circle
        cx='185'
        cy='134'
        fill='url(#pricingGradient6)'
        r='6'
      />

      {/* Trophy/achievement icon */}
      <path
        d='M95 40C95 35 100 30 110 30C120 30 125 35 125 40V45H95V40Z'
        fill='url(#pricingGradient7)'
      />
      <rect
        fill='url(#pricingGradient7)'
        height='15'
        rx='2'
        width='20'
        x='100'
        y='45'
      />
      <rect
        fill='url(#pricingGradient7)'
        height='8'
        width='10'
        x='105'
        y='60'
      />
      <rect
        fill='url(#pricingGradient7)'
        height='4'
        rx='2'
        width='16'
        x='102'
        y='68'
      />

      {/* Stars */}
      <path
        d='M50 50L52 56L58 56L53 60L55 66L50 62L45 66L47 60L42 56L48 56L50 50Z'
        fill='url(#pricingGradient8)'
        opacity='0.8'
      />
      <path
        d='M170 50L172 56L178 56L173 60L175 66L170 62L165 66L167 60L162 56L168 56L170 50Z'
        fill='url(#pricingGradient8)'
        opacity='0.8'
      />

      <defs>
        <linearGradient
          id='pricingGradient1'
          x1='0%'
          x2='100%'
          y1='0%'
          y2='100%'
        >
          <stop
            offset='0%'
            stopColor='#FF6B6B'
          />
          <stop
            offset='100%'
            stopColor='#4ECDC4'
          />
        </linearGradient>
        <linearGradient
          id='pricingGradient2'
          x1='0%'
          x2='100%'
          y1='0%'
          y2='100%'
        >
          <stop
            offset='0%'
            stopColor='#FF9500'
          />
          <stop
            offset='100%'
            stopColor='#FF6B6B'
          />
        </linearGradient>
        <linearGradient
          id='pricingGradient3'
          x1='0%'
          x2='100%'
          y1='0%'
          y2='100%'
        >
          <stop
            offset='0%'
            stopColor='#4ECDC4'
          />
          <stop
            offset='100%'
            stopColor='#FF9500'
          />
        </linearGradient>
        <linearGradient
          id='pricingGradient4'
          x1='0%'
          x2='100%'
          y1='0%'
          y2='100%'
        >
          <stop
            offset='0%'
            stopColor='#FF6B6B'
          />
          <stop
            offset='50%'
            stopColor='#FF9500'
          />
          <stop
            offset='100%'
            stopColor='#4ECDC4'
          />
        </linearGradient>
        <linearGradient
          id='pricingGradient5'
          x1='0%'
          x2='100%'
          y1='0%'
          y2='100%'
        >
          <stop
            offset='0%'
            stopColor='#4ECDC4'
          />
          <stop
            offset='100%'
            stopColor='#FF6B6B'
          />
        </linearGradient>
        <linearGradient
          id='pricingGradient6'
          x1='0%'
          x2='100%'
          y1='0%'
          y2='100%'
        >
          <stop
            offset='0%'
            stopColor='#FF9500'
          />
          <stop
            offset='100%'
            stopColor='#FF6B6B'
          />
        </linearGradient>
        <linearGradient
          id='pricingGradient7'
          x1='0%'
          x2='100%'
          y1='0%'
          y2='100%'
        >
          <stop
            offset='0%'
            stopColor='#FFD700'
          />
          <stop
            offset='100%'
            stopColor='#FF9500'
          />
        </linearGradient>
        <linearGradient
          id='pricingGradient8'
          x1='0%'
          x2='100%'
          y1='0%'
          y2='100%'
        >
          <stop
            offset='0%'
            stopColor='#4ECDC4'
          />
          <stop
            offset='100%'
            stopColor='#FF6B6B'
          />
        </linearGradient>
      </defs>
    </svg>
  );
};

export default PricingIcon;
